version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: my-custom-odoo-image
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - HOST=db
    volumes:
      - ./odoo/addons:/mnt/extra-addons

volumes:
  odoo-db-data: