export const ROUTES_APP = {
  login: "/login",
  profile: "/profile",
  home: "/",
  crm: {
    homeCRM: "/crm/home",
    customerList: "/crm/customerlist",
    customerDetail: "/crm/customerlist/:id",
    productPage: "/crm/productlist",
    contactList: "/crm/contactlist",
    contactDetail: "/crm/contactlist/:id",
    quotationList: "/crm/quotationlist",
    quotationDetail: "/crm/quotationlist/:id",
    opportunityList: "/crm/opportunitylist",
    opportunityDetail: "/crm/opportunitylist/:id",
    leadList: "/crm/leadlist",
    leadDetail: "/crm/leadlist/:id",
    contractList: "/contracts",
    contractDetail: "/contracts/:id",
    quoteList: "/quotes",
    quoteDetail: "/quotes/:id",
    debtReportList: "/crm/debtReportList",
    debtReportDetail: "/crm/debtReportList/:id",
  },
  hrm: {
    homeHRM: "hrm/home",
    employeeList: "/hrm/employee-list",
    employeeDetail: "/hrm/employee-list/:id",
    positionList: "/hrm/position-list",
    departmentList: "/hrm/department-list",
    assetList: "/hrm/asset-list",
    assetDetail: "/hrm/asset-list/:id",
  },
};
